/* SR-001 -> the build.
 *
 * The register is the source of truth for which sources may run. This script
 * reads it and writes the manifest the page enforces, so the answer to "why did
 * this source run" is a row somebody signed rather than a line somebody typed.
 *
 *   node tools/sr001-build.mjs ../../legal/SR-001-source-register.xlsx
 *
 * It rewrites the block between the SR001 markers in index.html. Nothing else
 * in the file is touched, and the script refuses to write a manifest whose
 * source names do not match the ones the build actually queries.
 */
import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';

const xlsx = process.argv[2] || path.resolve('../../legal/SR-001-source-register.xlsx');
const target = process.argv[3] || 'index.html';

/* openpyxl is here and a JS xlsx reader is not, so read it through python and
   keep the parsing in one place rather than adding a dependency for one file. */
const py = `
import json,sys
from openpyxl import load_workbook
wb=load_workbook(sys.argv[1], data_only=True)
ws=wb["SR-001 Register"]
head=[c.value for c in ws[1]]
ix={h:i for i,h in enumerate(head)}
out=[]
for row in ws.iter_rows(min_row=2, values_only=True):
    if not row[ix["Source name"]]: continue
    out.append({
      "id":   row[ix["Source ID"]],
      "name": str(row[ix["Source name"]]).strip(),
      "tier": row[ix["Tier"]],
      "status": (row[ix["Operational status"]] or "DISABLED pending classification").strip(),
      "legal":  (row[ix["Legal review status"]] or "NOT REVIEWED").strip(),
      "crit":   (row[ix["Criticality"]] or "").strip(),
      "person": (str(row[ix["Person-level output allowed?"]] or "NO")).strip().upper(),
    })
print(json.dumps(out))
`;
const rows = JSON.parse(execFileSync('python3', ['-c', py, xlsx], { encoding: 'utf8', maxBuffer: 32e6 }));

const enabled = rows.filter(r => r.status === 'ENABLED');
const person  = enabled.filter(r => r.person === 'YES');

/* Every source the build queries must appear on the register. A source in the
   code and not on the register is the exact thing OPS-001 s.12 forbids, and
   finding it here is cheaper than finding it in an audit. */
const html = fs.readFileSync(target, 'utf8');
const cats = eval(html.match(/var CATS\s*=\s*(\[[\s\S]*?\n\]);/)[1].replace(/<\/?b>/g, ''));
const inBuild = new Set();
cats.forEach(c => (c.src || []).forEach(s => inBuild.add(String(s[0]).trim())));
const onRegister = new Set(rows.map(r => r.name));
const missing = [...inBuild].filter(n => !onRegister.has(n));
if (missing.length) {
  console.error('REFUSING TO WRITE. ' + missing.length + ' source(s) run in the build and are not on SR-001:');
  missing.slice(0, 20).forEach(n => console.error('  ' + n));
  process.exit(1);
}

const manifest = {
  generated: new Date().toISOString().slice(0, 10),
  register: path.basename(xlsx),
  total: rows.length,
  enabled: enabled.map(r => r.name),
  critical: enabled.filter(r => r.crit === 'CRITICAL').map(r => r.name),
  personOutput: Object.fromEntries(person.map(r => [r.name, true])),
};

const OPEN = '/* SR001-MANIFEST-START generated by tools/sr001-build.mjs, do not edit by hand */';
const CLOSE = '/* SR001-MANIFEST-END */';
const block = OPEN + '\nvar SR001 = ' + JSON.stringify(manifest, null, 1) + ';\n' + CLOSE;
const re = new RegExp(OPEN.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&') + '[\\s\\S]*?'
                    + CLOSE.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&'));
if (!re.test(html)) { console.error('markers not found in ' + target); process.exit(1); }
fs.writeFileSync(target, html.replace(re, block));

console.log('SR-001 -> ' + target);
console.log('  on the register   ' + rows.length);
console.log('  enabled           ' + enabled.length);
console.log('  critical          ' + manifest.critical.length);
console.log('  person output     ' + person.length);
console.log('  in the build       ' + inBuild.size + ' (all on the register)');
if (!enabled.length) console.log('\n  Nothing is enabled, so nothing is in scope. That is the register working,\n  not a bug. Fill in the yellow cells and set Operational status to ENABLED.');
